# Generated by Django 3.2.6 on 2021-08-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='test', max_length=250),
            preserve_default=False,
        ),
    ]
